Terminiden1:
  weapon1: "Stalwart"
  weapon2: "MG-Gesch端tz"
  weapon3: "Napalm-Oribitalsperrfeuer"
  weapon4: "ADLER-500KG-Bombe"
Roboter1: 
  weapon1: "Panzerabwehrstellung"
  weapon2: "r端ckstossfreies Gewehr"
  weapon3: "Orbital-Laser"
  weapon4: "Raketengesch端tz"
Illuminierten1:
  weapon1: "Adler-Tieffliegerangriff"
  weapon2: "r端ckstossfreies Gewehr"
  weapon3: "Quasarkanone"
  weapon4: "Orbital-Gasangriff"